### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tposney** [johnnolan/fvtt-encounter-stats#111]
HI, like the module a lot - much richer than the midi roll stats. I'll put a reference to the module in the midi readme.md.
**Describe the bug**
It is possible (for example with a DamageOnlyWorkflow) for workflow.item to be undefined. This causes an error in 
```
function FormatMidiQol(workflow) {
  const wf = {
    _id: workflow._id,
    actor: {
      _id: workflow.actor._id,
    },
    item: {
      _id: workflow.item._id,
    },
```
It should probably guard references to workflow.item.

**What version of FoundryVTT are you using?**
Version 0.8.9/9.231

**Do you use any of these modules and are they active?**

[] midi-qol

**To Reproduce**
Use the midi-qol sample item Divine Smite, which does a DamageOnlyWorkflow and see the error thrown from FormatMidiQol

**Comment by johnnolan** [comment]
Thanks a lot for the bug report, really appreciate it! Putting in a fix now with a task to relook at the item lookup and see if I can smarten the midi parser a little more once I get some time to dig through the flows a bit.
