### ISSUE TITLE
Feature: Add separate damage for same AOE and multiple target damage. And maybe support for half-damage

### ISSUE THREAD

**Issue by Sravdar** [johnnolan/fvtt-encounter-stats#28]
For example when a burning hands hits 3 target with for full 10 damage make it log 30 damage instead of 10. If its 2 fail and 1 save then 25 damage instead of 10.

Maybe possible solution sugestion 1: Instead of loging damage from chat rolls loging changes in HP for all tokens after aoe or mulitple target damage rolled and then using it as damage for the attack.

Maybe possible solution sugestion 2: Adding promt button to chat after AOE or multiplte target spell where only DM can access to enter saves counts (full damage, half damage, no damage).

**Comment by johnnolan** [comment]
Thanks for this suggestion, its ace. Out of interest, do you use midi-qol? I am trying to support as many integrations as possible while maintaining feature parity hence the chat message log. I think your suggestion of monitoring the tokens damage may be the way forward for users who dont use midi-qol for targeting, etc

**Comment by johnnolan** [comment]
Yeah I agree with that, definitely part of the fun and your process is the same as I run my games too. Okay great, thanks, that gives me plenty to think about and a good use case moving forward, thank you
