### ISSUE TITLE
Damage not computing in stats

### ISSUE THREAD

**Issue by Avitale34** [johnnolan/fvtt-encounter-stats#31]
Maybe I am doing something wrong but all the damage stats are coming out 0 in the journal entry. using 8.6.
![image](https://user-images.githubusercontent.com/65961637/121224996-141bac80-c857-11eb-9fa1-f884d732e22e.png)

**Comment by johnnolan** [comment]
Hi, thanks for reporting this and reaching out, can I ask what modules you use that would change the chat messages on your game? Things like Better Rolls for 5e or midi-qol? Also their version numbers? I have a feeling something is changing the data in them and causing issues with getting the correct data out.

**Comment by Avitale34** [comment]
I am using the new version of Midi QOL  8.11 but no better rolls or anything like that I can think of

**Comment by johnnolan** [comment]
That helped alot, think I found the issue, going to get some time over the next few days/week and adjust the code to cope with as many configurations of MIDI-QOL as I can

**Comment by johnnolan** [comment]
I have released an update that now focusses on midi-qol in 0.8.0. 

Going to close this for now but please reopen if you are still having issues and if so could you take a screenshot of your Chat Log please so I can see what is being rolled?
