### ISSUE TITLE
Attacks not being recorded if used through Token Action HUD or Macro hotbar

### ISSUE THREAD

**Issue by Avitale34** [johnnolan/fvtt-encounter-stats#39]
I noticed the other day that the only stats for attacks that were being recorded were the ones being rolled directly from the character sheet. Most of the time my players and I use hotbars or the module Token Action Hud because it's faster. Any chance you could add this compatibility?

**Comment by johnnolan** [comment]
Hi, thanks for raising and feeding back! I noticed an issue with this on our game last night too. I am looking at it now and will hopefully have something out in the next day or two. Will link the updates and release to this issue so you can see how its going!

**Comment by johnnolan** [comment]
That should work now from my testing, if not I would love to hear back as its a bit of a black box when releasing things as to how people are getting on with it, thanks again!
