### ISSUE TITLE
Damage totals not showing for attacks

### ISSUE THREAD

**Issue by Avitale34** [johnnolan/fvtt-encounter-stats#47]
Hey I am using Token Action Hud and it seems like the damage numbers are not being recorded.

![image](https://user-images.githubusercontent.com/65961637/122935033-03cafd80-d33e-11eb-9af4-78bc35295f64.png)

**Comment by johnnolan** [comment]
Hi, thanks for raising. A few questions so I can replicate this side if you dont mind?

Do you use any of these modules as well as Token Hud?

* DDB Gamelog
* Beyond20
* Better Rolls for 5e
* midi-qol
* Minimal Rolling Enhancements

and also do you mind posting a screenshot of your chat log at all please?

Thanks in advance

**Comment by Avitale34** [comment]
I am just running Midi QoL out of the listed modules.
[fvtt-log-Tue-Jun-22-2021.txt](https://github.com/johnnolan/fvtt-encounter-stats/files/6695363/fvtt-log-Tue-Jun-22-2021.txt)

**Comment by Avitale34** [comment]
I am using 8.7 foundry, my fighter in my group uses a trident and also used TAH the whole combat and this is what their block looks like. Doesn't seem to be catching any weapon attacks. 
![image](https://user-images.githubusercontent.com/65961637/122976709-abf2bd80-d362-11eb-84db-97154a3f2b4c.png)

Same with the Rouge
![image](https://user-images.githubusercontent.com/65961637/122976809-c88ef580-d362-11eb-9fe5-be30919cd385.png)

**Comment by johnnolan** [comment]
Thank you, leave it with me and I will try and reproduce and find out what it is asap 👍

**Comment by johnnolan** [comment]
Found the issue after digging deep, thanks again for raising this and answering my questions, its a bit of a dark whole when releasing these modules as to what is happening for users.

If this doesn't work then feel free to reopen the issue.

Release: 0.12.1
