### ISSUE TITLE
[BUG] Doesn't log damage if have both midi-qol and better-rolls-for-5e

### ISSUE THREAD

**Issue by Sravdar** [johnnolan/fvtt-encounter-stats#58]
Version 0.8.8
DND5e 1.3.6

[] Better Rolls for 5e
[] midi-qol

1. Use "better rolls for 5e" for chat rollls.
2. In options have auto roll attack-roll but do NOT auto-roll damage
3. Make a attack roll (item in this case) and 
4. It doesn't log new rolled damage.

**Expected behavior**
I excpect it to log damage roll.

**Screenshots**
https://prnt.sc/198kf1b

**Additional context**
I'm aware it's stated it might not work if both midi-qol and better rolls are active but is it not possible to have selection between in settings of module or something?

**Debug output from modules settings**
`{"coreVersion":"0.8.8","modules":[{"key":"aacontent","id":"aacontent","name":"aacontent","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.5","version":"1.0.0"},{"key":"about-time","id":"about-time","name":"about-time","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.5","version":"1.0.3"},{"key":"ActiveAuras","id":"ActiveAuras","name":"ActiveAuras","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.5","version":"0.3.03"},{"key":"advanced-macros","id":"advanced-macros","name":"advanced-macros","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.5","version":"1.9"},{"key":"adventuremusic","id":"adventuremusic","name":"adventuremusic","active":false,"compatibleCoreVersion":"1.0.0","minimumCoreVersion":"0.5.0","version":"1.1.0"},{"key":"ae-to-chat","id":"ae-to-chat","name":"ae-to-chat","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.4","version":"0.3.1"},{"key":"arbron-hp-bar","id":"arbron-hp-bar","name":"arbron-hp-bar","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.7.9","version":"2.0.3"},{"key":"ATL","id":"ATL","name":"ATL","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.3","version":"0.2.16"},{"key":"autoanimations","id":"autoanimations","name":"autoanimations","active":false,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.7.9","version":"0.4.06"},{"key":"baileywiki-maps","id":"baileywiki-maps","name":"baileywiki-maps","active":false,"compatibleCoreVersion":"0.7.9","minimumCoreVersion":"0.6.0","version":"0.2.7"},{"key":"betterrolls5e","id":"betterrolls5e","name":"betterrolls5e","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.6","version":"1.5.4"},{"key":"betterroofs","id":"betterroofs","name":"betterroofs","active":false,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.6","version":"0.9.3.6"},{"key":"breaktime","id":"breaktime","name":"breaktime","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.0","version":"1.0.8"},{"key":"caeora-maps-tokens-assets","id":"caeora-maps-tokens-assets","name":"caeora-maps-tokens-assets","active":false,"compatibleCoreVersion":"0.7.9","minimumCoreVersion":"0.7.7","version":"1.0.4"},{"key":"CautiousGamemastersPack","id":"CautiousGamemastersPack","name":"CautiousGamemastersPack","active":false,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.7.9","version":"0.2.6"},{"key":"colorsettings","id":"colorsettings","name":"colorsettings","active":true,"compatibleCoreVersion":"0.8.1","minimumCoreVersion":"0.5.5","version":"2.5.9"},{"key":"combat-carousel","id":"combat-carousel","name":"combat-carousel","active":false,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.5","version":"0.2.1"},{"key":"combat-utility-belt","id":"combat-utility-belt","name":"combat-utility-belt","active":false,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.8.5","version":"1.6.0"},{"key":"CommunityLighting","id":"CommunityLighting","name":"CommunityLighting","active":true,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.8.6","version":"0.4.7"},{"key":"compendium-browser","id":"compendium-browser","name":"compendium-browser","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.6.2","version":"0.5.0"},{"key":"compendium-folders","id":"compendium-folders","name":"compendium-folders","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.2","version":"2.3.2"},{"key":"ct-effect-tooltips","id":"ct-effect-tooltips","name":"ct-effect-tooltips","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.5","version":"2.0.0"},{"key":"cursor-hider","id":"cursor-hider","name":"cursor-hider","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.6","version":"1.2.0+0.8.6"},{"key":"Custom-Token-Animations","id":"Custom-Token-Animations","name":"Custom-Token-Animations","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.5","version":"0.2.51"},{"key":"dae","id":"dae","name":"dae","active":true,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.8.4","version":"0.8.28"},{"key":"dd-import","id":"dd-import","name":"dd-import","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.4","version":"2.1.0"},{"key":"designerdoors","id":"designerdoors","name":"designerdoors","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.6","version":"2.0.0"},{"key":"df-architect","id":"df-architect","name":"df-architect","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.6","version":"2.0.2"},{"key":"df-curvy-walls","id":"df-curvy-walls","name":"df-curvy-walls","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.6","version":"3.2.0"},{"key":"df-settings-clarity","id":"df-settings-clarity","name":"df-settings-clarity","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.7.9","version":"3.2.0"},{"key":"dfreds-convenient-effects","id":"dfreds-convenient-effects","name":"dfreds-convenient-effects","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.6","version":"1.5.1"},{"key":"dfreds-droppables","id":"dfreds-droppables","name":"dfreds-droppables","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.6","version":"1.2.7"},{"key":"dfreds-pocket-change","id":"dfreds-pocket-change","name":"dfreds-pocket-change","active":false,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.6","version":"2.0.5"},{"key":"dice-calculator","id":"dice-calculator","name":"dice-calculator","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.7.5","version":"0.6.9"},{"key":"dice-so-nice","id":"dice-so-nice","name":"dice-so-nice","active":false,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.8.4","version":"3.4.2"},{"key":"drag-ruler","id":"drag-ruler","name":"drag-ruler","active":true,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.8.5","version":"1.7.5"},{"key":"DragTransfer","id":"DragTransfer","name":"DragTransfer","active":true,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.7.9","version":"1.2.1"},{"key":"dragupload","id":"dragupload","name":"dragupload","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.6","version":"2.0.0"},{"key":"DrawingTokenizer","id":"DrawingTokenizer","name":"DrawingTokenizer","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.6","version":"2.1.0"},{"key":"Dynamic-Effects-SRD","id":"Dynamic-Effects-SRD","name":"Dynamic-Effects-SRD","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.5","version":"5.0.01"},{"key":"easy-target","id":"easy-target","name":"easy-target","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.6","version":"2.12"},{"key":"enhanced-terrain-layer","id":"enhanced-terrain-layer","name":"enhanced-terrain-layer","active":true,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.8.0","version":"1.0.31"},{"key":"everybody-look","id":"everybody-look","name":"everybody-look","active":false,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.8.7","version":"2.0.0"},{"key":"foundryvtt-simple-calendar","id":"foundryvtt-simple-calendar","name":"foundryvtt-simple-calendar","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.7.9","version":"v1.2.113"},{"key":"foundry_community_macros","id":"foundry_community_macros","name":"foundry_community_macros","active":true,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.7.10","version":"0.43.0"},{"key":"foundry_community_tables","id":"foundry_community_tables","name":"foundry_community_tables","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.7.10","version":"0.15.0"},{"key":"furnace","id":"furnace","name":"furnace","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.7.7","version":"2.6.1"},{"key":"fvtt-encounter-stats","id":"fvtt-encounter-stats","name":"fvtt-encounter-stats","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.5","version":"0.14.0"},{"key":"fxmaster","id":"fxmaster","name":"fxmaster","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.5","version":"1.2.0"},{"key":"gm-notes","id":"gm-notes","name":"gm-notes","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.5.5","version":"0.4.1"},{"key":"gm-screen","id":"gm-screen","name":"gm-screen","active":true,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.8.3","version":"2.7.1"},{"key":"illandril-chat-enhancements","id":"illandril-chat-enhancements","name":"illandril-chat-enhancements","active":false,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.5","version":"1.2.1"},{"key":"illandril-token-tooltips","id":"illandril-token-tooltips","name":"illandril-token-tooltips","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.5","version":"2.3.0"},{"key":"initiative-double-click","id":"initiative-double-click","name":"initiative-double-click","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.4","version":"1.0"},{"key":"JB2A_DnD5e","id":"JB2A_DnD5e","name":"JB2A_DnD5e","active":false,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.7.0","version":"0.2.2"},{"key":"lessfog","id":"lessfog","name":"lessfog","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.7.4","version":"0.8.5"},{"key":"lib-df-hotkeys","id":"lib-df-hotkeys","name":"lib-df-hotkeys","active":true,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.7.9","version":"2.3.4"},{"key":"lib-wrapper","id":"lib-wrapper","name":"lib-wrapper","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.6.5","version":"1.7.5.0"},{"key":"lootpopulatornpc5e","id":"lootpopulatornpc5e","name":"lootpopulatornpc5e","active":false,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.5","version":"0.2.2"},{"key":"lootsheetnpc5e","id":"lootsheetnpc5e","name":"lootsheetnpc5e","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.5","version":"3.1.0"},{"key":"mad-cartographer-free-maps","id":"mad-cartographer-free-maps","name":"mad-cartographer-free-maps","active":false,"compatibleCoreVersion":"1.0.0","minimumCoreVersion":"0.6.0","version":"1.0.1"},{"key":"magicitems","id":"magicitems","name":"magicitems","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.6","version":"2.1.1"},{"key":"michaelghelfi","id":"michaelghelfi","name":"michaelghelfi","active":false,"compatibleCoreVersion":"0.7.9","minimumCoreVersion":"0.6.6","version":"1.2"},{"key":"midi-qol","id":"midi-qol","name":"midi-qol","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.4","version":"0.8.30"},{"key":"minimal-ui","id":"minimal-ui","name":"minimal-ui","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.3","version":"1.0.4"},{"key":"mobile-improvements","id":"mobile-improvements","name":"mobile-improvements","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.6.2","version":"1.0.2"},{"key":"monks-little-details","id":"monks-little-details","name":"monks-little-details","active":true,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.8.0","version":"1.0.34"},{"key":"multilevel-tokens","id":"multilevel-tokens","name":"multilevel-tokens","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.7","version":"1.5.2"},{"key":"music-d20-sampler","id":"music-d20-sampler","name":"music-d20-sampler","active":false,"compatibleCoreVersion":"0.7.0","minimumCoreVersion":"0.5.0","version":"1.0.0"},{"key":"Next-Up","id":"Next-Up","name":"Next-Up","active":false,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.5","version":"0.1.05"},{"key":"overhead-tile-fade-for-all-tokens","id":"overhead-tile-fade-for-all-tokens","name":"overhead-tile-fade-for-all-tokens","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.8","version":"0.2.0"},{"key":"parallaxia","id":"parallaxia","name":"parallaxia","active":true,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.8.7","version":"0.3.6"},{"key":"perfect-vision","id":"perfect-vision","name":"perfect-vision","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.7.8","version":"1.9.14"},{"key":"pin-cushion","id":"pin-cushion","name":"pin-cushion","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.6","version":"1.5.0"},{"key":"pings","id":"pings","name":"pings","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.6.6","version":"1.2.12+0.8.6"},{"key":"plutonium","id":"plutonium","name":"plutonium","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.4","version":"1.31.1"},{"key":"resourcesplus","id":"resourcesplus","name":"resourcesplus","active":false,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.5.5","version":"1.6.10"},{"key":"select-tool-everywhere","id":"select-tool-everywhere","name":"select-tool-everywhere","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.2","version":"1.2.0"},{"key":"sequencer","id":"sequencer","name":"sequencer","active":false,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.7.9","version":"0.4.6"},{"key":"settings-extender","id":"settings-extender","name":"settings-extender","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.4.4","version":"1.1.6+0.8.6"},{"key":"SharedVision","id":"SharedVision","name":"SharedVision","active":false,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.7.6","version":"1.0.6"},{"key":"simplefog","id":"simplefog","name":"simplefog","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.5","version":"0.1.18"},{"key":"smalltime","id":"smalltime","name":"smalltime","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.7.9","version":"1.9.9"},{"key":"socketlib","id":"socketlib","name":"socketlib","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.7.9","version":"1.0.8"},{"key":"SocketSettings","id":"SocketSettings","name":"SocketSettings","active":true,"compatibleCoreVersion":"0.8.5","minimumCoreVersion":"0.6.0","version":"0.0.5"},{"key":"SoundBoard","id":"SoundBoard","name":"SoundBoard","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.6.2","version":"1.5.2"},{"key":"SoundBoard-BlitzFreePack","id":"SoundBoard-BlitzFreePack","name":"SoundBoard-BlitzFreePack","active":false,"compatibleCoreVersion":"0.8.5","minimumCoreVersion":"0.6.2","version":"1.0.0"},{"key":"soundfxlibrary","id":"soundfxlibrary","name":"soundfxlibrary","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.6.0","version":"1.0.1"},{"key":"spellTemplateManager","id":"spellTemplateManager","name":"spellTemplateManager","active":false,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.6","version":"2.1.0"},{"key":"split-journal","id":"split-journal","name":"split-journal","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.4","version":"1.1"},{"key":"tabletop-rpg-music","id":"tabletop-rpg-music","name":"tabletop-rpg-music","active":false,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.6.5","version":"1.3.0"},{"key":"template-wall-collision","id":"template-wall-collision","name":"template-wall-collision","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.5","version":"1.0.3"},{"key":"terrain-ruler","id":"terrain-ruler","name":"terrain-ruler","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.6","version":"1.3.1"},{"key":"theatre","id":"theatre","name":"theatre","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.6","version":"1.17.0"},{"key":"tidy-ui_game-settings","id":"tidy-ui_game-settings","name":"tidy-ui_game-settings","active":true,"compatibleCoreVersion":"0.8.3","minimumCoreVersion":"0.7.0","version":"0.1.23"},{"key":"tidy5e-sheet","id":"tidy5e-sheet","name":"tidy5e-sheet","active":true,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.8.3","version":"0.5.10"},{"key":"times-up","id":"times-up","name":"times-up","active":true,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.8.2","version":"0.8.10"},{"key":"tips","id":"tips","name":"tips","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.6.0","version":"21.05.3"},{"key":"token-action-hud","id":"token-action-hud","name":"token-action-hud","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.0","version":"1.1.12"},{"key":"token-attacher","id":"token-attacher","name":"token-attacher","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.6","version":"4.1.2"},{"key":"token-info-icons","id":"token-info-icons","name":"token-info-icons","active":false,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.0","version":"2.3.2"},{"key":"token-mold","id":"token-mold","name":"token-mold","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.4","version":"2.13.1"},{"key":"token-variants","id":"token-variants","name":"token-variants","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.7.7","version":"1.11.0"},{"key":"tokenmagic","id":"tokenmagic","name":"tokenmagic","active":true,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.6","version":"0.5.2"},{"key":"touch-vtt","id":"touch-vtt","name":"touch-vtt","active":false,"compatibleCoreVersion":"0.8.7","minimumCoreVersion":"0.5.0","version":"1.8.0"},{"key":"turnmarker","id":"turnmarker","name":"turnmarker","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.6","version":"2.8.1"},{"key":"VoiceActor","id":"VoiceActor","name":"VoiceActor","active":false,"compatibleCoreVersion":"0.7.9","minimumCoreVersion":"0.7.0","version":"0.0.9"},{"key":"vtta-tokenizer","id":"vtta-tokenizer","name":"vtta-tokenizer","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.7.9","version":"3.2.5"},{"key":"walls-have-ears","id":"walls-have-ears","name":"walls-have-ears","active":false,"compatibleCoreVersion":"0.8.6","minimumCoreVersion":"0.8.5","version":"0.0.4"},{"key":"weatherblock","id":"weatherblock","name":"weatherblock","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.8.5","version":"0.6.2"},{"key":"zsync","id":"zsync","name":"zsync","active":true,"compatibleCoreVersion":"0.8.8","minimumCoreVersion":"0.7.2","version":"0.0.4"}],"settings":[{"id":"betterrolls5e.migration","value":{"status":false,"version":"1.5.4"}},{"id":"betterrolls5e.d20Mode","value":1},{"id":"betterrolls5e.damagePromptEnabled","value":true},{"id":"betterrolls5e.rollButtonsEnabled","value":true},{"id":"betterrolls5e.imageButtonEnabled","value":true},{"id":"betterrolls5e.altSecondaryEnabled","value":true},{"id":"betterrolls5e.applyActiveEffects","value":true},{"id":"betterrolls5e.quickDefaultDescriptionEnabled","value":false},{"id":"betterrolls5e.d20RollIconsEnabled","value":true},{"id":"betterrolls5e.defaultRollArt","value":"actor"},{"id":"betterrolls5e.rollTitlePlacement","value":"1"},{"id":"betterrolls5e.damageTitlePlacement","value":"1"},{"id":"betterrolls5e.damageContextPlacement","value":"1"},{"id":"betterrolls5e.damageRollPlacement","value":"2"},{"id":"betterrolls5e.contextReplacesTitle","value":true},{"id":"betterrolls5e.contextReplacesDamage","value":false},{"id":"betterrolls5e.critBehavior","value":"1"},{"id":"betterrolls5e.critString","value":"Crit"},{"id":"betterrolls5e.chatDamageButtonsEnabled","value":"1"},{"id":"betterrolls5e.playRollSounds","value":true},{"id":"betterrolls5e.hideDC","value":"0"},{"id":"fvtt-encounter-stats.enable","value":true},{"id":"fvtt-encounter-stats.enable_aoe_damage","value":false},{"id":"midi-qol.EnableWorkflow","value":true},{"id":"midi-qol.ItemRollButtons","value":false},{"id":"midi-qol.ItemDeleteCheck","value":true},{"id":"midi-qol.showGM","value":true},{"id":"midi-qol.ForceHideRoll","value":false},{"id":"midi-qol.AutoFastForwardAbilityRolls","value":false},{"id":"midi-qol.CriticalDamage","value":"default"},{"id":"midi-qol.DragDropTarget","value":false},{"id":"midi-qol.ConfigSettings","value":{"gmAutoAttack":true,"gmAutoFastForwardAttack":true,"gmAutoDamage":"none","gmAutoFastForwardDamage":false,"speedItemRolls":false,"speedAbilityRolls":false,"showItemDetails":"none","itemTypeList":["weapon","equipment","consumable","tool","loot","class","spell","feat","backpack"],"autoRollAttack":true,"autoFastForward":"attack","autoTarget":"none","autoCheckHit":"none","autoCheckSaves":"none","hideRollDetails":"none","displaySaveDC":true,"checkSaveText":false,"defaultSaveMult":0.5,"autoRollDamage":"none","autoApplyDamage":"none","damageImmunities":"none","requireMagical":false,"autoItemEffects":false,"rangeTarget":"none","playerRollSaves":"none","playerSaveTimeout":0,"rollNPCSaves":"auto","mergeCard":false,"mergeCardCondensed":false,"useTokenNames":false,"requireTargets":false,"fumbleSound":"none","diceSound":"none","criticalSound":"none","itemUseSound":"none","spellUseSound":"none","weaponUseSound":"none","potionUseSound":"none","fullAuto":false,"useCustomSounds":false,"customSoundsPlaylist":"9fEyPVIunD0aA0Hm","keyMapping":{"DND5E.Advantage":"altKey"},"allowUseMacro":true,"rollOtherDamage":false,"removeButtons":"all","gmRemoveButtons":"all","concentrationAutomation":true,"singleConcentrationRoll":true,"removeConcentration":false,"optionalRulesEnabled":false,"itemRollStartWorkflow":false,"usePlayerPortrait":false,"optionalRules":{"invisAdvantage":true,"checkRange":true,"nearbyFoe":5,"nearbyAllyRanged":4,"incapacitated":true,"removeHiddenInvis":true,"maxDRValue":false,"distanceIncludesHeight":false},"keepRollStats":false,"saveStatsEvery":20,"playerStatsOnly":false,"soptionalRulesEnabled":false,"requiresTargets":"none"}},{"id":"midi-qol.AddChatDamageButtons","value":"none"},{"id":"midi-qol.ColoredBorders","value":"none"},{"id":"midi-qol.AutoRemoveTargets","value":"dead"},{"id":"midi-qol.playerControlsInvisibleTokens","value":false},{"id":"midi-qol.Debug","value":"none"},{"id":"midi-qol.RollStats","value":{}}]}`

**Comment by johnnolan** [comment]
Thanks for that debug info, helped massively in replicating the issue fast, PR building now and releasing soon
