### ISSUE TITLE
[QUESTION] No journal entry appears after an encounter

### ISSUE THREAD

**Issue by remiverdel** [johnnolan/fvtt-encounter-stats#83]
Hi,

I was wondering were I was supposed to find the journal entry created after the encounter.
I tried to make multiple encounters as a GM playing player characters and it seems that nothing was created.

I have "Monk's Enhanced Journal" (tried to deactivate it but it didn't change the result)
I also have installed Better Rolls for 5e.

Thanks!

**Comment by remiverdel** [comment]
Oops, sorry for the "bug" label, wanted to tag it as a question. I don't know how to change that afterwards

**Comment by johnnolan** [comment]
Hey man, thanks so much for raising this, needed more coffee before I released the latest version and missed a piece of code. That should work now, do you mind updating to the latest version and see if it works for you?

**Comment by remiverdel** [comment]
Your damn fast! Trying it right now.

**Comment by remiverdel** [comment]
It works!
Just a strange thing, the journal entry gets created on the beginning of the combat and pops up on my screen. But it’s not a real problem, it can just add to the overall clutter on my end.
I’m French, would you want a French translation for your module?

Cheers,
Remi

**Comment by johnnolan** [comment]
Fantastic! And oh yes please, if you have the time I would love it being translated. I will add an issue and assign you. 

I will also pop a config option so you can optionally decide whether to see that popup. Thanks again man!

**Comment by remiverdel** [comment]
Great!
By the way, I saw that the timing format wasn’t appropriately synced to my timezone. Is it something that is tied to the module and could be changed or is it tied to Foundry itself?

Thx

**Comment by johnnolan** [comment]
Ah man I hate datetimes. It is currently set to ISO so a global time. There is a way to make it localised but I need to have a think on the nicest way. Good catch though, will add it to another ticket I have on the naming convention around the entries and how I can automate them somehow to be a bit more descriptive. #76 

Just released a new version so the notification is optional and off by default #87

**Comment by remiverdel** [comment]
Great news,

Just uploaded the translation on the ticket btw

**Comment by remiverdel** [comment]
Just noticed that even when the new option you added is unchecked, it still displays a popup with the journal entry when the settings text suggest that you need to check it to see the popup!
I’m also adding the translation for that

**Comment by johnnolan** [comment]
Morning! Have you got a screen shot you can put here or on Discord so I can see what message is appearing? 

Adding that translation now
