### ISSUE TITLE
[Feature] Add french translation

### ISSUE THREAD

**Issue by johnnolan** [johnnolan/fvtt-encounter-stats#85]
@remiverdel if you have the time, you can track your updates through this ticket, thank you for your help!

**Comment by remiverdel** [comment]
{
    "FVTTEncounterStats.opt_enable_name": "Activer FVTT Encounter Stats",
    "FVTTEncounterStats.opt_enable_hint": "Active le module FVTT Encounter Stats",
    "FVTTEncounterStats.enable_aoe_damage_name": "Activer le suivi des dégâts de zone",
    "FVTTEncounterStats.enable_aoe_damage_hint": "Quand actif, pour chaque sort qui utilise un gabarit de zone, le module prendra en compte tous les dégâts reçus par les tokens dans la zone au lieu de ne prendre en compte que les dégâts lancés au dé.",
    "FVTTEncounterStats.enable_monster_stats_name": "Activer le suivi des statistiques des Monstres/PNJ",
    "FVTTEncounterStats.enable_monster_stats_hint": "Choisis de ne suivre uniquement les stats des joueurs ou de tous les combattants.",
    "FVTTEncounterStats.opt_compendium_link_enable_name": "Activer la liaison avec les Compendiums",
    "FVTTEncounterStats.opt_compendium_link_enable_hint": "Remplace les noms des sorts/armes avec un lien vers l'article cet item dans le Compendium. Désactivez si vous avez "undefined" dans vos stats d'attaques.",
    "FVTTEncounterStats.opt_compendium_link_system_name": "Préfixe du Compendium",
    "FVTTEncounterStats.opt_compendium_link_system_hint": "Le motif est : 'dnd5e.items.fCRftM4QxEDkeu0a' où dnd5e est le subtext entre crochet dans le groupe de Compendiums.",
    "FVTTEncounterStats.template.most_damage_overall": "Le plus de dégâts au total",
    "FVTTEncounterStats.template.most_damage_per_turn": "Le plus de dégâts en 1 tour",
    "FVTTEncounterStats.template.highest_average_damage": "Le plus de dégâts en moyenne",
    "FVTTEncounterStats.template.highest_damage_in_1_hit": "Le plus de dégâts en 1 coup",
    "FVTTEncounterStats.template.kills": "Kills",
    "FVTTEncounterStats.template.most_kills": "Le plus de Kills",
    "FVTTEncounterStats.template.most_healing": "Le plus d'Actions de Soins",
    "FVTTEncounterStats.template.most_support_actions": "Le plus d'Actions de Soutien",
    "FVTTEncounterStats.template.battlefield_actions": "Le plus d'Actions en combat",
    "FVTTEncounterStats.template.enemies": "Ennemis",
    "FVTTEncounterStats.template.hp": "PV",
    "FVTTEncounterStats.template.startinghp": "PV de départ",
    "FVTTEncounterStats.template.finalhp": "PV de fin",
    "FVTTEncounterStats.template.ac": "CA",
    "FVTTEncounterStats.template.damage_total": "Total",
    "FVTTEncounterStats.template.isCritical": "Critique",
    "FVTTEncounterStats.template.min_damage": "Dégâts Min",
    "FVTTEncounterStats.template.max_damage": "Dégâts Max",
    "FVTTEncounterStats.template.avg_damage": "Dégâts Moy",
    "FVTTEncounterStats.template.round": "Round",
    "FVTTEncounterStats.template.weapon_spell_name": "Nom Arme/Sort",
    "FVTTEncounterStats.template.advantage": "Avantage",
    "FVTTEncounterStats.template.disadvantage": "Désavantage",
    "FVTTEncounterStats.template.attack_total": "Total d'Attaques",
    "FVTTEncounterStats.template.rounddmg": "Dégâts du Round",
    "FVTTEncounterStats.template.dmg": "DMG",
    "FVTTEncounterStats.template.attacks": "Attaques",
    "FVTTEncounterStats.template.health": "Santé",
    "FVTTEncounterStats.template.rolltype": "Type de jet",
    "FVTTEncounterStats.template.type": "Type",
    "FVTTEncounterStats.actiontypes.heal": "Soin",
    "FVTTEncounterStats.actiontypes.msak": "Attaque au CàC avec un Sort",
    "FVTTEncounterStats.actiontypes.rsak": "Attaque à distance avec un Sort",
    "FVTTEncounterStats.actiontypes.mwak": "Attaque au CàC",
    "FVTTEncounterStats.actiontypes.rwak": "Attaque à distance",
    "FVTTEncounterStats.actiontypes.save": "Sauvegarde",
    "FVTTEncounterStats.actiontypes.other": "Autre",
    "FVTTEncounterStats.config.debug": "Rapporter un Bug"
}

**Comment by remiverdel** [comment]
There is a few terms that lack context in English to properly translate in french, so I did my best. I guess I'll get the context of each text better when I see it in game. If there are approximation I'll edit them here afterwards!

**Comment by remiverdel** [comment]
"FVTTEncounterStats.opt_notification_created_name": "Afficher une notification quand une entrée dans le journal est créée",
